#!/bin/bash
set -e

sed -i 's:github.com/OpenZWave:github.com/ChristianKuehnel:g' Makefile
sed -i 's:github.com/OpenZWave:github.com/ChristianKuehnel:g' *.py 
sed -i 's:github.com/OpenZWave:github.com/ChristianKuehnel:g' src-api/openzwave/*.py

