#!/bin/bash
set -e

sed -i 's:github.com/OpenZWave:github.com/ChristianKuehnel:g' Makefile *.py src-api/openzwave/*.py
sed -i 's:githubusercontent.com/OpenZWave:githubusercontent.com/ChristianKuehnel:g' Makefile *.py src-api/openzwave/*.py


